-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 00:08:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Datos` (
  `idDatos` INT NOT NULL AUTO_INCREMENT,
  `TempAmb` VARCHAR(45) NOT NULL,
  `HumSue` VARCHAR(45) NOT NULL,
  `HumAir` VARCHAR(45) NOT NULL,
  `Lum` VARCHAR(45) NOT NULL,
  `Hour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDatos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
